env:
  global:
  - AUTHOR_EMAIL=catalin.cirstoiu@gmail.com
  - REGISTRY_USERNAME=catac
  - REGISTRY=index.docker.io
  - secure: BYHR93T+t00xp5aXiKNd6NVReiGbIq01Llwt0Hiu8b0lByVSdvWZLMTZJpypwATHTK8C/Mvvlug9w6EHieopdDnd58d5buEsyuMtv79EgERm8DK2U2+VWceDTrHPnKbV6njTgcHQ18km3AU3EfbotCh7hQftJSCFjxHUtBMF24VymP5EQecJyh42iIwitnZiGp6q7sQUUZz/9lr7SS+WLywtQ4xrG2BkjzJIhJ+KavFtlQW4NhLmyJkfbdPkBagER16+gXD+LaOc3QrrhRkSIGn1ojqVqi+O8NZlGoK2s9AdVK7cXlawQ3in5irug2eHnDN9Yh0xfj+nsSTy3bedPYV6ESjlZTQ2+JCMCbxEIYCfsOonNSkacLW0/Asq8p4048uhVumUpoDcu8DCmvAG4YRn9JS4cwZXmfDCzWPwzRAlAvzVO9s+k5+yuC2vXwjlkoBynW0O0x5TeiuTYIAM4ZgQbh1LtQa/h1FEGm7+yoCNbTqLB8QtuOAecInyFqu2+M2iMsIDvKh8ZIt9bhwt9YEh0Ge8tED0SruNkdsypMz08SoQ/chTTpyeozgIFqA5rH47nMWzak98mmh87AHImGM/WoNiB93jie8OfQy71Y7pE1uvn8gguRxowAAUQ8c9RbWVWigq2i68cbaKaXBinzb5LLTdIB3kOI15OX5t++E=
services:
- docker
language: go
go:
- 1.9.1
install:
- go get github.com/Masterminds/glide
script:
- make test
- if ([[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} != "true" ]])
  || [[ -n ${TRAVIS_TAG} ]]; then docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD}
  -e ${AUTHOR_EMAIL} ${REGISTRY}; VERSION="latest" make docker-release; fi
before_deploy:
- NAME=GOOS=linux GOARCH=amd64 go build -o bin/vault-lego-linux-amd64
after_deploy:
- docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD} -e ${AUTHOR_EMAIL}
  ${REGISTRY}
- VERSION=$TRAVIS_TAG make docker-release
deploy:
  provider: releases
  skip_cleanup: true
  on:
    repo: catac/vault-lego
    tags: true
  api_key:
    secure: "${GITHUB_TOKEN}"
  file: bin/vault-lego-linux-amd64
