env:
  global:
  - AUTHOR_EMAIL=gambol99@gmail.com
  - REGISTRY_USERNAME=gambol99+rebotbuilder
  - REGISTRY=quay.io
  - secure: bLPah5chMCs3QXz3lEZE/vlN+66tkEkgDRvfwVAa5vqdaNEIwJJVf5Jc2PBlFfhDpHnTC13HBKVtFeiHa7YFxoZce6wEFZkEJcUna8qZ+aE6gDXfUGV1E+wRYcZ8fWkaEr0KQ6qlVUw8gQvec/nWL7WjtQASQ3BosBZOnkUTCFFpFlesHmKooK+FwSHGHDk3580QJTB3YKDuCgTSLTrLdmt+j9XJTy0glzqxRAj2/cTK8Giq4ZCEHkfUog0YzUlK0AfQawbR0HJEhEuwlWEjAQQTtBVLJP62RNXjZzdCgRM3fW+AgI2OJcKK8bcqmleVjXMrASh310yd8Neq3SHZVu/WMOuIHVu7xG2ntXEPKxxQO/9iWSZwoiGC/HSX8MdFeeTz+bSoGe+BGAJTqyodHLmLRbfbtJRdzaa6i5onVkG7ZqumJXhNKnBrwzLz/k4yYSVz/TLilT5hyTyRLiOgjUTmO2iWVGRX5ECnFfiM3U85GPNZRGWyfYBlP7u48eF+EBvVmS/+rD/EjcRhgxCPVRnCPMnC4sLiqp7eChpRblWPXLWmcEXrt/ma1Gb4vwKoWCgndV+u10EOQSzJbyfs+aTNkl8iYtKOFlg3Vj7IvMNnu6lfeoVPIDXbYMlLO5NK0+sWgepn9N42LhVfFc+Smg2+7uTzEApds2J4jmQdrZE=
services:
- docker
language: go
go:
- 1.7
install:
- go get github.com/Masterminds/glide
script:
- make test
- if ([[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} != "true" ]])
  || [[ -n ${TRAVIS_TAG} ]]; then docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_TOKEN}
  -e ${AUTHOR_EMAIL} ${REGISTRY}; VERSION="latest" make docker-release; fi
before_deploy:
- NAME=GOOS=linux GOARCH=amd64 go build -o bin/vault-lego-linux-amd64
after_deploy:
- docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_TOKEN} -e ${AUTHOR_EMAIL} ${REGISTRY}
- VERSION=$TRAVIS_TAG make docker-release
deploy:
  provider: releases
  skip_cleanup: true
  on:
    repo: gambol99/vault-lego
    tags: true
  api_key:
    secure: Gcn1ggyZ96yeSAoBfMf5Gpkki4aCcDaJ0KcCnfLdvfs09iK174OUUgmNQPDJy53KlqzjBUcKCzKQ5BQde7O8LHuDF2yJLrUNqm4VRLPIdXt2dVkUWldwomk+RlMBbEhJdXuiqEMnpgpeGx0bU15xDlLA1w7sB7lNyaYVuOvr8abdhfinhO5vnT5XLeNTJ9byWU4lQbBThJmkLPtE6GTcuag04WuRcnNeV7tvnJb1R3m81i7mIUmTa2T3Xc2dpWX/IkGi8ROOcloEbQyMROyShGFVoMsGpTn9BlWaTt1RqXdlHSa8nJCiRSI2qOD9DnlD+g/xAIQbagUmh5N1nE4K+xKzkUXMfbAK3AkesnHI6unXSNA/e7C2Q8yyilP8sNcntzrkMoELxwGUCCfqbSp1wjMnPJw2zyzvuFKVlcneekPfmSHCJWNW4o/Y3qRAFaJSUYGhdf7KZ67hYEfr1CkjvrmpEbbNB/E8t1bMj6Fs6Yi++u2Y3CFj4fi3Pt8rGw2TcPb2q4fn3cr8gCri01mZz/UqdkKZegQgXwb7lhEmubmujgKM5ycbP+/1TnJ6Q0jisAaTcgcwb5lzenbM+euVdsRFqrZl8354aclbknw5bqVFTPngqzLRS/nKBqNqDI2iy6c6dmqRBS7csM0cCo84dME7qEYJQUM557YFVLylajw=
  file: bin/vault-lego-linux-amd64
