env:
  global:
  - secure: Gcn1ggyZ96yeSAoBfMf5Gpkki4aCcDaJ0KcCnfLdvfs09iK174OUUgmNQPDJy53KlqzjBUcKCzKQ5BQde7O8LHuDF2yJLrUNqm4VRLPIdXt2dVkUWldwomk+RlMBbEhJdXuiqEMnpgpeGx0bU15xDlLA1w7sB7lNyaYVuOvr8abdhfinhO5vnT5XLeNTJ9byWU4lQbBThJmkLPtE6GTcuag04WuRcnNeV7tvnJb1R3m81i7mIUmTa2T3Xc2dpWX/IkGi8ROOcloEbQyMROyShGFVoMsGpTn9BlWaTt1RqXdlHSa8nJCiRSI2qOD9DnlD+g/xAIQbagUmh5N1nE4K+xKzkUXMfbAK3AkesnHI6unXSNA/e7C2Q8yyilP8sNcntzrkMoELxwGUCCfqbSp1wjMnPJw2zyzvuFKVlcneekPfmSHCJWNW4o/Y3qRAFaJSUYGhdf7KZ67hYEfr1CkjvrmpEbbNB/E8t1bMj6Fs6Yi++u2Y3CFj4fi3Pt8rGw2TcPb2q4fn3cr8gCri01mZz/UqdkKZegQgXwb7lhEmubmujgKM5ycbP+/1TnJ6Q0jisAaTcgcwb5lzenbM+euVdsRFqrZl8354aclbknw5bqVFTPngqzLRS/nKBqNqDI2iy6c6dmqRBS7csM0cCo84dME7qEYJQUM557YFVLylajw=
  - AUTHOR_EMAIL=gambol99@gmail.com
  - REGISTRY_USERNAME=gambol99+rebotbuilder
  - REGISTRY=quay.io
  - secure: JtsQxtIoTWkAMhmMi4wPRPB6bZUNG6Qi81aEV3QEkwDMKJZmUeyf0tQ83vUjfeKOj1LMItSZX7zzhgk3NpNVWQAk82TospZD4BUyzdhBRNDwfHfVHDrbapCt3j7y+jaBdUQxMNiIdAK7llgHpMJtFostAe2PATshYRobMgBHwWc9krLvQmgFwboMBy6WLrZQjqBOZJmB3y/WSBiKnfEJMlgmuj1mCKVNtt9Jzj0ts/yvI8bSRx091vgFDwmZQXSK91neL2cQKVJ5S8j4Pp/MvGIRllKxq1jhaLSu4coTdJoHwufIfNAgYrG2/qBwELWCXhaRMQHyrhak3VbVP1jY/UkpIXwSAtxK4dCeX6ar1wK71PsewY84PDoyMJ8k32NoVdpNfxKaKLPiK5HEFdpI3OmsDOBlEFfRIdf1pC6f3ROnrHB6Ob+jL6c6y09l2Xv0uQq63QuIefeCkLDuA9EOioz8JdDBGBQSWOvB/SamiCzQVF1kZHWZNkA/CGikKQPlei3LBLD2GUAx8eGF5qoFouKkAlIvznHotiyjGposURvgO5MrTqa/zBrdgRYA0rGna1PYiyFKko/Ui3QL6fr6ixNf1JpD89jwyKFoGO7uvBf3MeuicMGUMeCGR8C2VjUQG5jLPAAtGC5zPGSBI7zc+5/WG9TMIiKk+6F19G3McFc=
services:
- docker
language: go
go:
- 1.7
install:
- go get github.com/Masterminds/glide
script:
- make test
- if ([[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} != "true" ]])
  || [[ -n ${TRAVIS_TAG} ]]; then docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_TOKEN}
  -e ${AUTHOR_EMAIL} ${REGISTRY}; VERSION="latest" make docker-release; fi
before_deploy:
- NAME=GOOS=linux GOARCH=amd64 go build -o bin/vault-lego-linux-amd64
after_deploy:
- docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_TOKEN} -e ${AUTHOR_EMAIL} ${REGISTRY}
- VERSION=$TRAVIS_TAG make docker-release
deploy:
  provider: releases
  skip_cleanup: true
  on:
    repo: gambol99/vault-lego
    tags: true
  api_key:
    secure: "${GITHUB_TOKEN}"
  file: bin/vault-lego-linux-amd64
